### ISSUE TITLE
Cached pages bypass htmlcompressor middleware

### ISSUE THREAD

**Issue by Rembrant** [rails/actionpack-page_caching#10]
I am using actionpack-page_caching to cache static pages and the htmlcompressor gem as middleware ( https://github.com/paolochiodi/htmlcompressor ). When I look at my Rails server's response source code in Chrome DevTools it is compressed but when I look at the source of my Page Cached file it is not compressed.

How would this best be fixed? Thanks.

**Comment by pixeltrix** [comment]
Closing because as @weynsee says, this is because it's written to disk in a controller action before it is returned to the Rack middleware so to fix it would require rewriting as Rack middleware which @weynsee has already done so there doesn't seem much point 😄
