### ISSUE TITLE
expire_page doesn't seem to work with controller and action

### ISSUE THREAD

**Issue by ianwalter** [rails/actionpack-page_caching#24]
The documentation makes it seem like you can do:

``` ruby
expire_page controller: 'home', action: 'index'
```

But this doesn't seem to work. The page isn't being expired.
Also, after looking through the tests, it seems only expiring a page with a custom route is tested?

``` ruby
expire_page '/index.html'
```

**Comment by jronallo** [comment]
I'm also experiencing this issue.

**Comment by DamirSvrtan** [comment]
Bump. @fxn @rafaelfranca ?

**Comment by Vorob-Astronaut** [comment]
+1

**Comment by jmarbach** [comment]
+1

**Comment by pixeltrix** [comment]
The `expire_page` method passes an options hash to `url_for` so it'll look for whatever that generates with the special case of looking for `/index` plus whatever the default extension is (typically `.html`).

If this isn't happening then please provide an example.

**Comment by fxn** [comment]
It's been more than three years here. Please if you can provide a cocrete example to reproduce the problem feel free to open an issue again.
