### ISSUE TITLE
Please expand on web server configuration comment

### ISSUE THREAD

**Issue by trak3r** [rails/actionpack-page_caching#25]
"Page caching works by configuring a web server to first check for the existence of files on disk, and to serve them directly when found, without passing the request through to Action Pack."

Could you please expand on that or perhaps link to external sources explaining how that is accomplished for some mainstream web servers like Apache? 

I'd be happy to submit a pull request to embellish the documentation if somebody can point me towards where to find the information.

Thank you.

**Comment by fascox** [comment]
@trak3r i found this for nginx. http://www.rubytutorial.io/page-caching-with-rails4/
maybe this help

**Comment by nilbus** [comment]
I created a [wiki page](https://github.com/rails/actionpack-page_caching/wiki) on this project with examples for Apache and Nginx, borrowed from #27 with tweaks.
