### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by schuylr** [rails/actionpack-page_caching#31]
Will this gem be supported in Rails 5? Currently the `gemspec` states:

```
gem.add_dependency 'actionpack', '>= 4.0.0', '< 5'
```

which doesn't support `5.0.0.beta1`

**Comment by kaspth** [comment]
We'll gladly accept pull requests. Thanks 😁

**Comment by schuylr** [comment]
I may have time in the future to help - however, why close this issue?

Rails 5 is at the beta stage and more people are going to ask - a closed issue reduces awareness. IMO it should only be closed once this is resolved in a pull request.

**Comment by kaspth** [comment]
> I may have time in the future to help

Great, that's very cool if you can! :heart:

About closing, I don't see the benefit of having an issue open if no one is doing anything about it.

**Comment by schuylr** [comment]
@kaspth It didn't take much doing - just some updates to dependencies and tests. The core library works fine as-is. I've squashed all my commits into a single one as well.

One issue I'm having is that the tests will break between 4.0 and 4.1 due to `render text` throwing deprecation warnings in 5.0. I can either:

* Put `render text` back and keep the deprecation warnings in the tests (for now)
* Ignore failures for 4.0 or remove Gemfile-4-0-stable 
* Bump the gemspec to require `actionpack >= 4.1.0` and update the README to state Rails 4.0 is supported in version `1.0.2`

Let me know how I should proceed.

**Comment by kaspth** [comment]
Sweet! Thanks for making it happen, it seems @eileencodes is already on it 😎

**Comment by januszm** [comment]
👍
