### ISSUE TITLE
Rails 5 status?

### ISSUE THREAD

**Issue by kieraneglin** [rails/actionpack-page_caching#35]
I'm creating a Rails 5 JSON API, and since the `cache!` method is broken in jbuilder. this seems like just the thing.

I see there are existing PRs and closed issues, but is there any update on when this'll work with Rails 5?

**Comment by pedropaf** [comment]
I'm trying to add this gem to a rails 5 website and also I'm getting errors on bundle Install:

Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 5.0.0)

  In Gemfile:
    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0)

    actionpack-action_caching was resolved to 1.0.0, which depends on
      actionpack (< 5.0, >= 4.0.0.beta)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 3.1.1, which depends on
        actionpack (>= 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Any Ideas? Thanks

**Comment by sai43** [comment]
@pedropaf  having same issue for me also. any solution?

**Comment by michaelholloway** [comment]
@pedropaf I'm having the same issue as well. When will action-caching work in Rails 5?

**Comment by rafaelfranca** [comment]
Closing in favor of https://github.com/rails/actionpack-page_caching/pull/41
