### ISSUE TITLE
New changes broke gem and it generate empty files

### ISSUE THREAD

**Issue by le0pard** [rails/actionpack-page_caching#42]
Hello. Looks like [this commit](https://github.com/rails/actionpack-page_caching/commit/43dd478916e8e22e2412150145c8a2990369db59) did something bad and gem start generate empty files. After switching to:

```
gem 'rails', '5.0.0.1'
gem 'actionpack-page_caching', git: 'https://github.com/rails/actionpack-page_caching', ref: '3180f5ee17c4d161c4739a3f9c2e34e01d7261b7'
```

All start working as expected (no empty files).

**Comment by pixeltrix** [comment]
@le0pard thanks - will take a look. The files are present just with no content?

**Comment by le0pard** [comment]
> The files are present just with no content?

Yep.

**Comment by pixeltrix** [comment]
@le0pard thanks for testing - would've been embarrassing for that one to go out in a release! 😄

**Comment by le0pard** [comment]
@pixeltrix thanks. Will test it today and notify about results.

**Comment by le0pard** [comment]
@pixeltrix confirmed, all fixed.
