### ISSUE TITLE
Rails 5.2 Support

### ISSUE THREAD

**Issue by verenion** [rails/actionpack-page_caching#45]
Is there any discussions about upgrading this to 5.2?

Currently using this gem with no sucess:

`gem "actionpack-page_caching",
    git: "https://github.com/kord-as/actionpack-page_caching",
    branch: "rails5"`

**Comment by Schwad** [comment]
What do you think @pixeltrix ?

**Comment by rafaelfranca** [comment]
What no success means? This gem show work with Rails 5.2. Can you be more specific about what is not working?

**Comment by fxn** [comment]
This issue seems to be stale.

We have applications on 5.2 using this gem. Please, if you have some specific incompatibility feel free to open an issue again with more detailed information.
