### ISSUE TITLE
Release a new version compatible with rails 6

### ISSUE THREAD

**Issue by thomasdziedzic** [rails/actionpack-page_caching#58]
The latest version that has been released is 1.1.1:
https://rubygems.org/gems/actionpack-page_caching/versions/1.1.1

This relies on actionpack < 6, which makes the version incompatible with rails 6.

I see git master is compatible with rails 6 so can you please release a new version like 1.2.0?

Thanks!

**Comment by le0pard** [comment]
cc @rafaelfranca

**Comment by joshuapaling** [comment]
For now this works:

```
gem 'actionpack-page_caching', github: 'rails/actionpack-page_caching'
```

**Comment by rafaelfranca** [comment]
1.2.0 was released
