### ISSUE TITLE
1.2.1 breaks homepage

### ISSUE THREAD

**Issue by GuillaumeWrobel** [rails/actionpack-page_caching#59]
Hello,

After update from 1.2.0 to 1.2.1, my homepage broke.

### Before
- www.my-website.com :ok:
- www.my-website.com/some-path :ok:

### After
- www.my-website.com :no_entry: 
- www.my-website.com/some-path :ok:

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by rafaelfranca** [comment]
Fixed on 1.2.2. Thank you for reporting

**Comment by GuillaumeWrobel** [comment]
hey @rafaelfranca sorry for the low-info report!
and a big-up for your quick fix.
