### ISSUE TITLE
Release notes or Changelog for new versions?

### ISSUE THREAD

**Issue by akegan** [rails/actionpack-page_caching#62]
I'm working to upgrade from 1.1.1 to 1.2.1 or beyond, but I'm having trouble finding documentation of the differences in the versions. I see a couple of releases under "releases", but the latest version is 1.0.1. The CHANGELOG seems to go up to 1.1.1. I see that there are some new tags beyond 1.1.1, but would like some context around what the changes are in the different versions. Is there more info on these versions somewhere else?

**Comment by robzolkos** [comment]
Yeah you're right - seems that has been skipped.  I'll see if I have time this week to do a PR to address.

For now you can compare between each tag

https://github.com/rails/actionpack-page_caching/compare/v1.1.1...v1.2.0
https://github.com/rails/actionpack-page_caching/compare/v1.2.0...v1.2.1
https://github.com/rails/actionpack-page_caching/compare/v1.2.1...v1.2.2
https://github.com/rails/actionpack-page_caching/compare/v1.2.2...v1.2.3
