### ISSUE TITLE
Update Cache per day.

### ISSUE THREAD

**Issue by crazypioneer** [rails/actionpack-page_caching#64]
How could I regenerate&update cached pages per day?

**Comment by robzolkos** [comment]
@crazypioneer the docs go through an efficient way of busting the cache [here](https://github.com/rails/actionpack-page_caching#full-cache-expiration)

In terms of timing, as its something that is handled at the server level not the Rails app I would probably schedule this using a nightly CRON job.

**Comment by crazypioneer** [comment]
Thank you for your kind.
As expected, CRON job....

**Comment by robzolkos** [comment]
This is a pretty good intruduction to cron https://www.google.com/amp/s/www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/amp/

**Comment by crazypioneer** [comment]
Thank you.
Not about CRON but about updating cache.
Should I run below command inside CRON JOB function?

tmp=public/cached_pages-$(date +%s)
mv public/cached_pages $tmp
rm -rf $tmp

**Comment by crazypioneer** [comment]
I used this.
Thank you.

FileUtils.rm_rf('dir/to/remove')
