### ISSUE TITLE
URI.parser is deprecated and will be removed in Rails 6.2

### ISSUE THREAD

**Issue by trak3r** [rails/actionpack-page_caching#67]
```
DEPRECATION WARNING: URI.parser is deprecated and will be removed in Rails 6.2. 
Use `URI::DEFAULT_PARSER` instead. (called from cache_file at 
.../lib/action_controller/caching/pages.rb:149)
```
https://github.com/rails/actionpack-page_caching/blob/master/lib/action_controller/caching/pages.rb#L149

**Comment by pixeltrix** [comment]
@trak3r I've pushed 1.2.4 of the gem which should remove this warning:
https://rubygems.org/gems/actionpack-page_caching/versions/1.2.4

Thanks for your report 👍🏻
