### ISSUE TITLE
Js stimulus, i18n and cache

### ISSUE THREAD

**Issue by Nodalailama** [rails/actionpack-page_caching#71]
Hi,

I use i18n js (https://github.com/fnando/i18n-js) in a stimulus controller attach to a div in a index's page which I have set caches_page :index in the controller.

I was thinking the js would only be execute on client side so that I can have i18n working depending on the lang the client set ... but it not seems working.

May I made an error ? 

Thanks.

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by Nodalailama** [comment]
Thanks for answering, I will ask on rails discuss.
